POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbG1hayIsImlkIjoiNjE2ZmZkOWM5MTgzMGZmZTYzODRmODYxIiwiaWF0IjoxNjM1MzIyMzI0fQ.P1zHeRCZNQ5c6Ca6MWdR81tuQmakcHmXNoVVr8DhoBg

{
  "title": "Testblog14",
  "author": "Author Catorce",
  "url": "https://someotherurl.com",
  "likes": 6
}
